# Generated by Django 4.2 on 2023-04-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_pieces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='image',
            field=models.ImageField(default='https://i.imgur.com/nQtyN1F.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='date_finished',
            field=models.DateField(verbose_name=()),
        ),
    ]
